name: Publish

on:
  push:
    branches:
      - main

jobs:
  publish:
    runs-on: ubuntu-latest
    name: Publish
    steps:
      - uses: actions/checkout@v4

      - uses: pnpm/action-setup@v4
        name: Install pnpm

      - uses: oven-sh/setup-bun@v2
      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          cache: 'pnpm'

      - name: Install packages
        run: pnpm install

      - name: Package
        run: pnpm vsce:package

      - name: Publish to open-vsx
        run: pnpx ovsx publish ottotime.vsix -p ${{ secrets.OPEN_VSX_TOKEN }}

        # https://dev.azure.com/ottomated/_usersSettings/tokens
      - name: Publish to vscode marketplace
        run: pnpm vsce publish -i ottotime.vsix -p ${{ secrets.VSCODE_ACCESS_TOKEN }}
